# GitHub Actions Workflow for Production Deployment
name: Deploy to Production Server

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Run on GitHub's virtual machine
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (optional but good practice)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: SSH to server and run deployment script
      - name: SSH and run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Full path to your deployment script on the server
            # Make sure deploy.sh file has execute permission (chmod +x deploy.sh)
            bash /root/shci-app/deploy.sh
